##### Bivariate Analysis

    Dataset: titanic_dataset.csv

    1. Numerical vs categorical: scatter plot, correlation
    2. Numerical vs categorical: box plot, group statistics
    3. Numerical vs categorical: crosstab, countplot

1. Setup

In [8]:
%pip install -q numpy pandas matplotlib scipy seaborn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr

sns.set_style("whitegrid")
pd.set_option('display.max_columns', 50)

2. Load dataset

In [10]:
data = sns.load_dataset('titanic')
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
data.shape

(891, 15)

In [13]:
data.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [15]:
data.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [16]:
# Identify numerical and categorical columns
numerical_cols = ['age', 'fare', 'sibsp', 'parch']  # Explicitly specify numerical columns
categorical_cols = ['survived', 'pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck','embark_town', 'alone']

print("Categorical Columns:", categorical_cols)
print("Numerical Columns:", numerical_cols)

Categorical Columns: ['survived', 'pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alone']
Numerical Columns: ['age', 'fare', 'sibsp', 'parch']

In [19]:
data.head()[numerical_cols]

    age     fare  sibsp  parch
0  22.0   7.2500      1      0
1  38.0  71.2833      1      0
2  26.0   7.9250      0      0
3  35.0  53.1000      1      0
4  35.0   8.0500      0      0

In [20]:
total_nulls = data[numerical_cols].isnull().sum()
print(total_nulls)

age      177
fare       0
sibsp      0
parch      0
dtype: int64

In [22]:
data_num = data[numerical_cols].dropna()

In [ ]:
nulls_after_dropna = data_num.isnull().sum()
print(nulls_after_dropna)
print("Numerical columns with nulls after dropna:", (nulls_after_dropna > 0).sum())

TypeError: Boolean array expected for the condition, not object